services:
    database:
        image: postgres:17.4
        shm_size: 1gb
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            POSTGRES_DB: $DB_DATABASE
        secrets:
            - postgres-passwd
        networks:
            - ventodoro
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ./psql/data:/var/lib/postgresql/data
        restart: always

networks:
    ventodoro:

secrets:
    postgres-passwd:
        environment: DB_PASSWORD
