services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        restart: always
        volumes:
            - ./:/var/www
        networks:
            - ventodoro
        ports:
            - 9000
        depends_on:
            - database
            - nginx
        environment:
            DB_HOST: database
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        ports:
            - "80:80"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
        command: >
            certonly --webroot
            --webroot-path=/var/www/acme-challenge
            --non-interactive
            --agree-tos
            --email ventodoro@yandex.ru
            -d admin.ventodoro.ru
        networks:
            - ventodoro

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
            - certbot
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt:ro
        networks:
            - ventodoro

    database:
        image: postgres:17.4
        shm_size: 1gb
        container_name: database
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            POSTGRES_DB: ${DB_DATABASE}
        secrets:
            - postgres-passwd
        networks:
            - ventodoro
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ./psql/data:/var/lib/postgresql/data
        restart: always

networks:
    ventodoro:
        driver: bridge

secrets:
    postgres-passwd:
        environment: DB_PASSWORD
