services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        restart: always
        volumes:
            - ./:/var/www
        networks:
            - ventodoro
        ports:
            - 9000
        depends_on:
            - database
            - nginx
        environment:
            DB_HOST: database
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - ventodoro

    database:
        image: postgres:17.4
        shm_size: 1gb
        container_name: database
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
            POSTGRES_DB: ${DB_DATABASE}
        secrets:
            - postgres-passwd
        networks:
            - ventodoro
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ./psql/data:/var/lib/postgresql/data
        restart: always

networks:
    ventodoro:
        driver: bridge

secrets:
    postgres-passwd:
        environment: DB_PASSWORD
